// <auto-generated />
namespace TableSplitting
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserAndAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAndAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201307130030197_UserAndAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
